import 'dart:convert';

/// The default ID length used by Nano ID.
const int defaultSize = 21;

/// Nano ID's default 64-character URL-safe alphabet.
///
/// Its ordering is retained from the JavaScript `ai/nanoid` package.
const String urlAlphabet =
    'useandom-26T198340PX75pxJACKVERYMINDBUSHWOLF_GQZbfghjklqvwyzrict';

/// Generates one deterministic Nano ID-style identifier from [seed].
///
/// The same seed, [size], and [alphabet] return the same output across
/// platforms and package executions. The generated ID is fixed-length, so
/// distinct seeds are not mathematically guaranteed to produce distinct IDs.
/// Use [encodeSeed] for a reversible, collision-free representation of unique
/// seed strings.
String nanoid({
  required String seed,
  int size = defaultSize,
  String alphabet = urlAlphabet,
}) => SeededNanoId(alphabet: alphabet, size: size).generate(seed);

/// Creates a reusable seeded generator using [alphabet] and [size].
///
/// This is the seeded counterpart to Nano ID's custom alphabet API.
SeededNanoId customAlphabet(String alphabet, {int size = defaultSize}) =>
    SeededNanoId(alphabet: alphabet, size: size);

/// A deterministic Nano ID-style generator.
///
/// Output bytes are derived from a specified non-cryptographic 32-bit stream.
/// This defines the package's version 1 generation algorithm and avoids
/// reliance on Dart's implementation-dependent seeded `Random` stream. See
/// the package README for the byte-level algorithm definition and stability
/// contract.
final class SeededNanoId {
  /// Creates a deterministic generator.
  ///
  /// [alphabet] must contain 1 to 256 distinct Unicode scalar values. [size]
  /// must be greater than zero.
  SeededNanoId({this.alphabet = urlAlphabet, this.size = defaultSize})
    : _symbols = _validateAlphabet(alphabet) {
    _validateSize(size);
  }

  /// The output alphabet used by this generator.
  final String alphabet;

  /// The default length of an identifier generated by this generator.
  final int size;

  final List<String> _symbols;

  /// Generates an identifier from the UTF-8 bytes of [seed].
  ///
  /// [size] overrides this generator's default length for one identifier.
  String generate(String seed, {int? size}) =>
      generateBytes(utf8.encode(seed), size: size);

  /// Generates an identifier directly from [seed] bytes.
  ///
  /// Byte seeds let callers supply an existing stable serialization without
  /// converting it to text first.
  String generateBytes(List<int> seed, {int? size}) {
    final outputSize = size ?? this.size;
    _validateSize(outputSize);

    final bytes = _SeededByteStream(seed);
    final cutoff = 256 - (256 % _symbols.length);
    final output = StringBuffer();
    var characters = 0;

    while (characters < outputSize) {
      final byte = bytes.nextByte();
      if (byte < cutoff) {
        output.write(_symbols[byte % _symbols.length]);
        characters++;
      }
    }

    return output.toString();
  }
}

List<String> _validateAlphabet(String alphabet) {
  final symbols = alphabet.runes.map(String.fromCharCode).toList();
  if (symbols.isEmpty) {
    throw ArgumentError.value(alphabet, 'alphabet', 'Must not be empty.');
  }
  if (symbols.length > 256) {
    throw ArgumentError.value(
      alphabet,
      'alphabet',
      'Must contain no more than 256 symbols.',
    );
  }
  if (symbols.toSet().length != symbols.length) {
    throw ArgumentError.value(
      alphabet,
      'alphabet',
      'Must not contain duplicate symbols.',
    );
  }
  return List<String>.unmodifiable(symbols);
}

void _validateSize(int size) {
  if (size <= 0) {
    throw RangeError.value(size, 'size', 'Must be greater than zero.');
  }
}

final class _SeededByteStream {
  _SeededByteStream(List<int> seed) {
    final state = _mixSeed(<int>[..._domain, ..._validatedBytes(seed)]);
    _a = state[0];
    _b = state[1];
    _c = state[2];
    _d = state[3];

    for (var round = 0; round < _warmupRounds; round++) {
      _nextWord();
    }
  }

  static const int _warmupRounds = 12;
  static final List<int> _domain = utf8.encode('seeded_nanoid/v1\x00');

  late int _a;
  late int _b;
  late int _c;
  late int _d;
  List<int> _wordBytes = const [];
  var _offset = 0;

  int nextByte() {
    if (_offset == _wordBytes.length) {
      final word = _nextWord();
      _wordBytes = <int>[
        word & 0xff,
        (word >>> 8) & 0xff,
        (word >>> 16) & 0xff,
        (word >>> 24) & 0xff,
      ];
      _offset = 0;
    }

    return _wordBytes[_offset++];
  }

  int _nextWord() {
    final word = _uint32(_a + _b + _d);
    _d = _uint32(_d + 1);
    _a = _uint32(_b ^ (_b >>> 9));
    _b = _uint32(_c + (_c << 3));
    _c = _uint32((_c << 21) | (_c >>> 11));
    _c = _uint32(_c + word);
    return word;
  }
}

List<int> _mixSeed(List<int> seed) {
  var h1 = 1779033703;
  var h2 = 3144134277;
  var h3 = 1013904242;
  var h4 = 2773480762;

  for (final byte in seed) {
    h1 = _uint32(h2 ^ _multiply32(h1 ^ byte, 597399067));
    h2 = _uint32(h3 ^ _multiply32(h2 ^ byte, 2869860233));
    h3 = _uint32(h4 ^ _multiply32(h3 ^ byte, 951274213));
    h4 = _uint32(h1 ^ _multiply32(h4 ^ byte, 2716044179));
  }

  h1 = _multiply32(h3 ^ (h1 >>> 18), 597399067);
  h2 = _multiply32(h4 ^ (h2 >>> 22), 2869860233);
  h3 = _multiply32(h1 ^ (h3 >>> 17), 951274213);
  h4 = _multiply32(h2 ^ (h4 >>> 19), 2716044179);
  h1 = _uint32(h1 ^ h2 ^ h3 ^ h4);
  h2 = _uint32(h2 ^ h1);
  h3 = _uint32(h3 ^ h1);
  h4 = _uint32(h4 ^ h1);

  return <int>[h1, h2, h3, h4];
}

int _multiply32(int left, int right) {
  final leftLow = left & 0xffff;
  final leftHigh = (left >>> 16) & 0xffff;
  final rightLow = right & 0xffff;
  final rightHigh = (right >>> 16) & 0xffff;
  final low = leftLow * rightLow;
  final middle = (leftHigh * rightLow + leftLow * rightHigh) & 0xffff;
  return _uint32(low + (middle << 16));
}

int _uint32(int value) => value & 0xffffffff;

List<int> _validatedBytes(List<int> bytes) {
  for (final byte in bytes) {
    if (byte < 0 || byte > 255) {
      throw RangeError.range(byte, 0, 255, 'seed byte');
    }
  }
  return List<int>.unmodifiable(bytes);
}
